### ISSUE TITLE
Test does not match task description [The cd builtin: Absolute paths]

### ISSUE THREAD

**Issue by andy1li** [codecrafters-io/shell-tester#17]
According to the [task description](https://app.codecrafters.io/courses/shell/stages/ra6):

> It'll also check whether the message `cd: <directory>: No such file or directory` is printed if the provided path is invalid.

But the test currently is:

```
fmt.Sprintf("match %q", fmt.Sprintf(`%s: No such file or directory\n`, directory))
```

It should be:

```
fmt.Sprintf("match %q", fmt.Sprintf(`cd: %s: No such file or directory\n`, directory)),
```

PR #16

**Comment by ryan-gang** [comment]
Fixed by #16.
